name: Python CI
description: Format, Lint and Test Python codebase
inputs:
  python-version:
    required: false
    default: 3.9
  uses_local_packages:
    required: false
    type: boolean
    default: false
  working-directory:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup python ${{ inputs.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}                 

    - name: Install dev requirements dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: python -m pip install -r ./dev_requirements.txt

    - name: Run pylint linter        
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: python -m pylint $(git ls-files "./**/*.py")

    - name: Run black formatter
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: python -m black . --check

    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: python -m pytest . -vv --junit-xml pytest.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ${{ inputs.working-directory }}/pytest.xml