name: Python CI
description: Format, Lint and Test Python codebase
inputs:
  python-version:
    required: false
    default: 3.8
  uses_local_packages:
    required: false
    type: boolean
    default: false    

runs:
  using: "composite"
  steps:
    - name: Setup python ${{ inputs.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}
        
    - name: Build & Install local packages
      working-directory: src/packages
      if: ${{ inputs.uses_local_packages }}
      run: | 
        python -m pip install wheel
        python -m pip install .                        

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Run pylint linter        
      run: python -m pylint $(git ls-files ./**/*.py)

    - name: Run black formatter
      run: python -m black . --check

    - name: Run tests
      run: python -m pytest .