name: End to end tests
description: Execute end to end tests based on target URLs
inputs:
  working-directory:
    description: Relative path to end to end tests
    required: false
    default: './src/tests'
    
  python-version:
    required: false
    default: 3.9

  function_app_one_name:
    required: true
    type: string
  
  function_app_one_key:
    required: true
    type: string
  
runs:
  using: "composite"
  steps:
  - name: Setup Python ${{ inputs.python-version }} Environment
    uses: actions/setup-python@v1
    with:
      python-version: ${{ inputs.python-version }}

  - name: Install dev requirements dependencies
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: python -m pip install -r ./dev_requirements.txt

  - name: Run end to end tests
    env:
      E2E_TESTS_function_app_one_name: ${{ inputs.function_app_one_name }}
      E2E_TESTS_function_app_one_key: ${{ inputs.function_app_one_key }}
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: python -m pytest . -vv