name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    defaults:
      run:
        working-directory: './infrastructure'
    env:
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}
      TF_VAR_secret_1: ${{ secrets.SECRET_1 }}
      TF_VAR_secret_2: ${{ secrets.SECRET_2 }}


    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'HashiCorp - Setup Terraform'
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Format
        run: terraform fmt -check

      - name: Init
        run: terraform init -backend-config="" -backend-config="${{environment}}.tfbackend"

      - name: Validate
        run: terraform validate -no-color

      - name: Plan
        run: terraform plan -var-file="${{ environment }}.tfvars" -no-color -out=plan.tfdata

      - name: Apply
        run: terraform apply -var-file="${{ environment }}.tfvars" -auto-approve plan.tfdata
