name: Function One CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/function_one/**'
      - '.github/workflows/function-one-ci.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'src/function_one/**'
      - '.github/workflows/function-one-ci.yml'

  # allow manually triggering
  workflow_dispatch:      


jobs:
  ci:
    name: Python CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
     
      - uses: actions/checkout@v2
        name: Checkout branch

      - name: Run lint, format and tests      
        uses: ./.github/actions/python-ci
        with:
          working-directory: './src/function_one'

